[package]
name = "tafar/abc"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Promise = "evaera/promise@4.0.0"
Comm = "sleitnick/comm@1.0.1"
Signal = "sleitnick/signal@2.0.3"
TableUtil = "sleitnick/table-util@1.2.1"
Tree = "sleitnick/tree@1.1.0"
Trove = "sleitnick/trove@1.5.0"
Loader = "sleitnick/loader@2.0.0"
Component = "sleitnick/component@2.4.8"
Lyra = "paradoxum-games/lyra@0.4.1"
Fusion = "plainsour/lemon@0.4.0-dev.1.1"
Charm = "littensy/charm@0.10.0"
CharmSync = "littensy/charm-sync@0.3.0"
PathUtil = "tafzri/path-util@0.1.0"
Shake = "sleitnick/shake@1.1.0"
Remo = "littensy/remo@1.5.2"
t = "osyrisrblx/t@3.1.1"
Reflex = "littensy/reflex@4.3.1"
Symbol = "sleitnick/symbol@2.0.1"
Ser = "sleitnick/ser@1.0.5"	
Spring = "sleitnick/spring@1.0.0"
Spr = "blackjackiee/spr@1.1.3"
Replica = "ldgerrits/replica@1.0.3"
Vide = "centau/vide@0.3.1"
Ripple = "littensy/ripple@0.9.2"

[server-dependencies]
ProfileStore = "lm-loleris/profilestore@1.0.3"