[package]
name = "paradoxum-games/lyra"
description = "Advanced player data management with a simple API"
version = "0.4.1"
license = "MIT"
authors = ["nomer888"]
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
homepage = "https://paradoxum-games.github.io/lyra/"
repository = "https://github.com/paradoxum-games/lyra"
exclude = ["*"]
include = [
	"src",
	"src/**/*",
	"wally.lock",
	"wally.toml",
	"LICENSE",
	"default.project.json",
]

[dependencies]
Promise = "evaera/promise@4.0.0"
t = "osyrisrblx/t@3.1.1"

[dev-dependencies]
Jest = "jsdotlua/jest@3.10.0"
JestGlobals = "jsdotlua/jest-globals@3.10.0"
