[package]
name = "blackjackiee/spr"
description = "Spr is a spring-based motion library by Fraktality. https://github.com/Fraktality/spr"
license = "MIT"
authors = ["Fraktality"]
version = "1.1.3"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
