[package]
name = "plainsour/lemon"
description = "personal upload. A modern reactive UI library, built specifically for Roblox and Luau --dev0.3"
license = "MIT"
authors = ["plainsour", "Elttob"]
version = "0.4.0-dev.1.4"

registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

exclude = ["**"]
include = ["src", "src/*", "default.project.json", "wally.lock", "wally.toml"]

[dependencies]